# Site settings
title: Larry Land
email: trivex@gmail.com
description: Larry Gadea's random ramblings
twitter:
  username: lg
social:
  name: Larry Gadea
  links:
    - https://twitter.com/lg
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lg.io" # the base hostname & protocol for your site
twitter_username: lg
github_username: lg
highlighter: rouge
timezone: America/Los_Angeles
future: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM

gems:
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap